Project double_iprate {
database_type: 'PostgreSQL'
Note: 'Beer Review Social Media mock'
}

Table users {
  id integer [primary key]
  username varchar
  user_thumbnail text 
  email text 
  password varchar 
  birthday date 
  city varchar 
  country varchar
  beer_sommelier boolean 
  facebook_id text 
  google_id text 
  created_at date
  updated_at date
 }

Table beer {
  id integer [primary key]
  beer_type integer 
  name varchar 
  type varchar 
  manufacturer_id varchar 
  rating_id integer 
  bottle_thumbnail text [note: 'graphic of ale']
  
}

Table manufacturer {
    id integer [primary key]
    name varchar 
    city_id integer 
    country_id integer 
}

Table beer_sommelier {
    id integer [primary key]
    name varchar 
    certification integer 
    publication varchar 
}


Table rating {
  id integer [primary key]
  user_id integer 
  beer_id integer 
  beer_sommelier_id integer
  review_id integer 
  reaction_id integer 
  malt decimal 
  yeast decimal
  hops decimal
  aromatic decimal
  pairing varchar // this could potentially become a new update to the app later
  lighting datetime
  season date // change to month in schema
}


Table reviews {
  id integer [primary key]
  user_id integer 
  beer_id integer 
  reaction_id integer
  beer_sommelier_id integer 
  created_at datetime
  review_duration integer
  friend_add_id integer 
  tag_id integer 
  share_id integer 
  share_time datetime
 }

 Table reaction {
   id integer [primary key]
   user_id integer 
   beer_sommelier_id integer 
   beer_id integer 
   reaction_thumbnail text [note: 'clip of reaction'] 
}

Table tags {
  id integer [primary key]
  user_id integer 
  beer_sommelier_id integer 
  beer_id integer 
  manufacturer_id integer 
}


Table platform {
  id integer [primary key]
  platform_type varchar 
}


Table shares {
  id integer [primary key]
  user_id integer 
  share_id integer 
  platform_id integer 
  review_id integer 
  created_at datetime
} 


Table cities {
  id integer [primary key]
  name varchar
  country_id integer

}

Table countries {
  id integer [primary key]
  country_code varchar
  country_name varchar
}



Ref: reviews.user_id > users.id

